### ISSUE TITLE
Implement Reduce2

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#162]
Make this a Program Template program that is driven by Phil parameters.  Match the Probe2 probe Phil parameters when they apply to both.

**Comment by russell-taylor** [comment]
(done) Leave the metalic atoms jumpered out in Reduce when computing the Probe score.

It may be that metallics are not jumpered out, just short-circuited for Histidine ahead of the Mover placement; check this.

Metals are added to an excluded points list in manageMetals(); the list is used to invalidate nearby atoms that overlap the metals during findCliques().  This looks like it probably avoids adding locked-down Movers to cliques, or at least locked-down atoms that touch metals.

Yeah, it looks like that is what "jumpered out" means, so we're already doing this with our special checks for flips.

We're not yet excluding them in the checks for clique overlaps (invalidating potential bumpers that come into contact with +ions), but this appears to only be used to cull clique memberships.  Leaving them in may cause additional Movers to be added to cliques, so we may need to fix this if our performance is too slow.

**Comment by russell-taylor** [comment]
The best score for each flipper when it was in the non preferred state is also recorded. Page 1746: can be run adding to put each flip in the non chosen state but everything else optimized to enable comparisons. It uses the header information from its previous output to determine which state to use.

**Comment by russell-taylor** [comment]
(done) His61 in 1XSO has two metals so no hydrogen added. Good test case.

More test cases from Jane:

Two of the cases were already in the early H-bond addition tests: 
- 3cp5 Cys 45 & Cys 48 to heme (HEC)
- 6vw1 Asn 90 ND2 to NAG C1 and NAG-to-NAG.

(other cases)
- O-linked carbohydrate:  3nk4 Thr 168 Og to A2G 
- SS-bond half-open:  1pq7 Cys 41 to Cys 57, alta is SS bond, altB is open
- Aminoacyl charged tRNA:  6hxv ribosome chain 1w, A-site tRNA with amino acid covalently bound to CCA end

Modified amino acids are presumably taken care of in their descriptions, but two to check are:
- 6t5h phosphoserine (SEP) 240  on fused peptide 238-242, chain A
- 4kw9 green fluorescent protein ligand (CRO) made from the protein chain - Leu 64 C to CRO 66 C1, CRO 66 C 1 to CRO 66 N 3, CRO 66 C 3 to Val 68 N

Interactions of protein with ions:
- 5dka Zn finger:  His 115 Ne2 and Cys 119 Sg with Zn 302
- 6tte beta-galactosidase chainA His 418 Nd1 with Mg A3001
- 2mbw myoglobin His 93 Ne2 with Fe in HEM

**Comment by russell-taylor** [comment]
Page 1743 describes flagging ambiguous cases in the output.

**Comment by russell-taylor** [comment]
(done) Pull out the Probe parameters and their parsing into Helper functions that are used by both the Probe2 and Reduce2 programs.  Make it report a subset of the Phil parameters that gets included by each and that get parsed by wrapper Python constructors.

(done) Replace the PHIL-based parameters in the helper functions with a phil structure.

**Comment by russell-taylor** [comment]
(done) Find out which command-line arguments MolProbity uses.

**Comment by russell-taylor** [comment]
(done) From molprobity/doc/dev_notes/reduce_in_Molprobity.txt: 
- (done) -quiet (done) -trim (done) -allalt
- (done) -nobuild9999
- (done) -build (done)-nuclear
- (done) -fix (used in the generation of flipkins)

From code inspection:
- (ignoring) -limit

**Comment by russell-taylor** [comment]
**@todo:** Running reduce2 on 4fen.pdb has errors during optimization.

**Comment by russell-taylor** [comment]
(done) Changing the preference magnitude from 1.0 to 9999.0 on 1xs0 produces the same results in either case.

The reported final states are different for some Movers, so it is not clear why the output models are the same... except that the output files have no hydrogens on them!  We were writing the original model, not the modified model, to disk.  Fixed.

**Comment by russell-taylor** [comment]
(done) Run on all alternate conformations, finishing with the first conformation so non-alternate ones will end up matching alternate A.  Looks like this happens already in the singleton optimizer so may happen in all, remove comment from main code if that is the case and add the equivalent of -onlya in, letting them select an alternate.

We get a crash in the second ("A) alternate of 1xs0 when we try to run on both.  Fixed this by re-initializing the atom cache for each alternate in the FastOptimizer.

**Comment by russell-taylor** [comment]
(done) There is consideration of metals during placement that modifies biases for radius checks and other things.
- (done) reduce.cpp:1470: This is being used to lock down the conformation of asn,gln,asx,glx.
- (done) reduce.cpp:1523: Hydrogens that are marked with BONDBUMPFLAG (looks like all polar hydrogens) that would overlap with atoms are not placed and warnings are issued (different bias for metals than for non-metals when checking for bumping during placement).  Asked Dorothee whether this is checked for in the hydrogen-placement code.  (This is only checked when the heavy atom that is bonded to the hydrogen is within a reasonable range to bond to the neighboring atom that the hydrogen would collide with -- asked Dorothy and Nigel whether the bond proxies will see this and the hydrogen placement will be avoided in this case.)  Jane is not sure that we still want this check, so I'll comment out the section of code that was to implement it until she decides otherwise.

**Comment by russell-taylor** [comment]
(done) Add ASX and GLX to the ASN and GLN residues that have HS2 flips.  Make sure that the flip code works in both cases (atom names and bonding) and then check for all four cases rather than just two in Optimizers.py in all places that we check.

The Mover code won't currently be able to handle atom type X when it is looking for neighbors and bonds.  1KP0 is an example structure with an ASX and GLX.

Just report when they are found but do not attempt to operate on them.

Note that CCTBX throws a "Sorry" when it encounters an atom of type X, so we won't need to deal with this in any case.

**Comment by russell-taylor** [comment]
(done) Running `mmtbx.reduce2 F:\data\Richardsons\1xso.cif output.description_file_name=deleteme.txt add_flip_movers=True` now causes a crash when trying to write the model as an mmcif (though it can write the file as a PDB):

```
Traceback (most recent call last):
  File "C:\tmp\cctbx-probe\build\..\modules\cctbx_project\mmtbx\command_line\reduce2.py", line 6, in <module>
    run_program(reduce2.Program)
  File "C:\tmp\cctbx-probe\modules\cctbx_project\iotbx\cli_parser.py", line 70, in run_program
    task.run()
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\programs\reduce2.py", line 200, in run
    txt = model.model_as_mmcif()
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\model\model.py", line 1550, in model_as_mmcif
    grm_geometry.pair_proxies(sites_cart)
  File "C:\tmp\cctbx-probe\modules\cctbx_project\cctbx\geometry_restraints\manager.py", line 1317, in pair_proxies
    sites_cart) > self.effective_nonbonded_buffer)):
RuntimeError: scitbx Internal Error: C:\tmp\cctbx-probe\modules\cctbx_project\scitbx\array_family\boost_python\flex_vec3_double.cpp(516): SCITBX_ASSERT(lhs.size() == rhs.size()) failure.
```

Re-processing the model without making restraints before making it into CIF seems to solve the problem.

**Comment by russell-taylor** [comment]
(done) Do not remove the Hydrogen in the NH2 case when there is a nearby ion.  Instead, lock down the orientation (which is what the original code does).

If the NH2 has the Nitrogen pointing at an +ion, Jane expects it to flip rather than removing the Hydrogen.

**Comment by russell-taylor** [comment]
**@todo:** Behavior of polar and non-polar Hydrogen addition checks. reduce.cpp:1523
- There should definitely be code to check what happens with non-polar Hydrogens.
    - Reduce currently leaves off the Hydrogen for ions (which is a mistake): 5a1a has ligand that gets too close to an ion.  It should instead put it on and call it a clash.
    - Reduce2 should always have these be placed when there are positive ions or negative ions (this will check for clash)
    - For non ions, it should do whatever Reduce is doing
- Polar Hydrogen code around line 305 in Optimizers.py
    - with a positive ion; you don't want the Hydrogen to be there, so do the same thing that Reduce does now
    - For negative ions, you do want the Hydrogen to be there
    - Keep it the way it is for atoms that are not ions

**Comment by russell-taylor** [comment]
(done) Reduce marks some (but not all) Water Oxygens as radius 0, no donor, no acceptor and marks others radius 1.40 with acceptor (but no donor?).  This differs from how Probe marks them, which is all acceptor+donor with radius 1.4.  We'll accept CCTBX's judgement on this.

**Comment by russell-taylor** [comment]
(moved) As of 12/21/2021, we are getting a lot of messages to the console of the form:
```
pdbres="NCO B 109 "
  Cannot extract axes_and_atoms_to_rotate:
    n_branches <= 2, n_branches: 4
```

These happen when running `mmtbx.reduce2 output.description_file_name=4fen_new.txt F:\data\Richardsons\4fen.pdb`

We're getting corresponding notifications in the Reduce2 output: "Could not add MoverNH3Rotator to chain B NCO 109: MoverNH3Rotator(): Partner does not have three bonded friends"

Created issue https://github.com/ReliaSolve/cctbx_project/issues/244 to deal with this.
