### ISSUE TITLE
Running reduce2 on 4fen.pdb has errors during optimization.

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/Molprobity2#165]
Added a raise when this happens so I could get a stack trace:

```
pdbres="NCO B 103 "
  Cannot extract axes_and_atoms_to_rotate:
    n_branches <= 2, n_branches: 4
Traceback (most recent call last):
  File "C:\tmp\cctbx-probe\build\..\modules\cctbx_project\mmtbx\command_line\reduce2.py", line 6, in <module>
    run_program(reduce2.Program)
  File "C:\tmp\cctbx-probe\modules\cctbx_project\iotbx\cli_parser.py", line 70, in run_program
    task.run()
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\programs\reduce2.py", line 158, in run
    altID=self.params.alt_id, preferenceMagnitude=self.params.preference_magnitude)
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\reduce\Optimizers.py", line 1003, in __init__
    minOccupancy = minOccupancy, preferenceMagnitude = preferenceMagnitude)
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\reduce\Optimizers.py", line 855, in __init__
    minOccupancy = minOccupancy, preferenceMagnitude = preferenceMagnitude)
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\reduce\Optimizers.py", line 744, in __init__
    minOccupancy = minOccupancy, preferenceMagnitude = preferenceMagnitude)
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\reduce\Optimizers.py", line 284, in __init__
    ret = _PlaceMovers(self._atoms, model.rotatable_hd_selection(iselection=True),
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\model\model.py", line 2476, in rotatable_hd_selection
    use_shortcut       = use_shortcut)
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\hydrogens\__init__.py", line 320, in rotatable
    helper_2(atoms, restraints_manager)
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\hydrogens\__init__.py", line 265, in helper_2
    tardy_model = tardy_model)
  File "C:\tmp\cctbx-probe\modules\cctbx_project\mmtbx\utils\rotatable_bonds.py", line 141, in axes_and_atoms_aa_specific
```

**Comment by russell-taylor** [comment]
These do not stop the processing, but they presumably are making is not place a Mover.

We get a lot of copies of the following:
```
pdbres="NCO B 109 "
  Cannot extract axes_and_atoms_to_rotate:
    n_branches <= 2, n_branches: 4
```

**Comment by russell-taylor** [comment]
Fixed by reducing the number of things we compute so that we don't see the problem.
